version: '3.9'

x-indexer-environment: &indexer-environment
  POSTGRES_HOST:
  POSTGRES_PORT:
  POSTGRES_USER:
  POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
  POSTGRES_DBNAME:
  TON_INDEXER_API_ROOT_PATH:
  TON_INDEXER_API_TITLE:

services:
  index-api:
    image: ${DOCKER_REGISTRY:-localhost:5000}/ton-indexer-cpp:${IMAGE_TAG:?}
    build:
      context: indexer
      dockerfile: Dockerfile
    secrets:
      - postgres_password
    command: gunicorn indexer.api.main:app -k uvicorn.workers.UvicornWorker --bind=0.0.0.0:8081 -w 1
    ports:
      - target: 8081
        published: ${TON_INDEXER_API_PORT:-8081}
        protocol: tcp
        mode: host
    environment: *indexer-environment 
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.${TONCENTER_ENV:?}.indexer-cpp.api==true"
    networks:
      internal:
      toncenter-global:
        aliases:
          - ${TONCENTER_ENV:?}-indexer-cpp-api

  materialized_views_refresher:
    build:
      context: indexer
      dockerfile: Dockerfile
    secrets:
      - postgres_password
    command: python3 refresh_materialized_view.py
    environment: *indexer-environment
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.${TONCENTER_ENV:?}.indexer-cpp.api==true"
    networks:
      internal:

networks:
  internal:
    attachable: true
    external: false
    driver_opts:
      com.docker.network.driver.mtu: 1350
  toncenter-global:
    external: true

secrets:
  postgres_password:
    file: private/postgres_password
  