version: '3.9'

x-indexer-environment: &indexer-environment
  POSTGRES_HOST:
  POSTGRES_PORT:
  POSTGRES_USER:
  POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
  POSTGRES_DBNAME:
  TON_INDEXER_API_ROOT_PATH:

services:
  index-api:
    image: ${DOCKER_REGISTRY:-localhost:5000}/ton-indexer:${IMAGE_TAG:?}
    build:
      context: indexer
      dockerfile: Dockerfile
    secrets:
      - postgres_password
    command: gunicorn indexer.api.main:app -k uvicorn.workers.UvicornWorker --bind=0.0.0.0:8081 -w 1
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
    environment: *indexer-environment 
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.${TONCENTER_ENV:?}.indexer.api==true"
    networks:
      internal:
      toncenter-global:
        aliases:
          - ${TONCENTER_ENV:?}-indexer-api

networks:
  internal:
    attachable: true
    external: false
  toncenter-global:
    external: true

secrets:
  postgres_password:
    file: private/postgres_password
  # tonlib_config:
  #   file: ${TON_INDEXER_LITESERVER_CONFIG:?}
